### ISSUE TITLE
 vu meter to match song dynamics and not current volume

### ISSUE THREAD

**Issue by MrGJones** [pimoroni/pivumeter#10]
is there a way to get the vu meter of the phatbeat to just match the dynamics of the song played and not the set volume? so that the leds are always lively even at low volumes?

**Comment by Gadgetoid** [comment]
This is something I'm looking into, although apparently it's due to a bug in the ALSA plugin framework where volume control is being applied *directly* to the audio stream, inadvertently and totally replacing the stream that the VU meter is working with.

I'm planning to implement a workaround; a slow moving average, that will adjust the VU meter to match the current volume without it changing too rapidly during the quiet parts of songs.

**Comment by MrGJones** [comment]
interesting idea! perhaps a slower dissolving meter that begins in the middle and grows up/down like a multi coloured kitt would be nice too

**Comment by Gadgetoid** [comment]
A fix for this- partially anyway- is buried within #15 and waiting to be merged. It's a vu-scale option which give you an optional upper limit against which to scale the VU intensity. This isn't sufficient for working at all volumes, and a more "correct" fix is required. I think that will come as part of the front-end Python implementations, however and may not be possible to support within the Pi VU Meter C code itself (which by virtue of being inserted into the ALSA audio chain really needs to be simple).
