### ISSUE TITLE
Crazy blinking when playing multiple streams

### ISSUE THREAD

**Issue by nicokaiser** [pimoroni/pivumeter#24]
When playing multiple (loud enough) streams e.g. through `aplay`, some LEDs start blinking randomly. Maybe there is an overflow somewhere?

**Comment by Gadgetoid** [comment]
I suspect this is more likely a race-condition between the multiple different instances of the Pi VU Meter plugin that playing multiple streams will create.

Since the plugin accesses the hardware directly, multiple streams will try to access the same hardware directly and in parallel which will no doubt ultimately cause some serious weirdness.

I still have a work in progress to move the hardware access out of the plugin and into a custom server, see: https://github.com/pimoroni/pivumeter/tree/devel/python_server  but this currently makes no attempt to resolve conflict between multiple streams.

I'd have thought dmix would mix the streams before they reach Pi VU Meter, but if I've learned anything about ALSA over the past few months it's that I have no idea how audio makes its way through ALSA and the various plugin chains setup therein. There appears to be no rhyme or reason to it.
